Merge layout
vladhillary/Wedding-shop-layout pull request #1
Opened 2021-09-16 09:09 UTC by vladhillary

added layout home page of maket, adaptivity for laptop(1024 px), mobile(320px) and desktop(>1920px).

2021-09-16 11:33 UTC, Aliaksandrlosich requested changes
Поработать над неймингом классов. Нейминг не информативен. Хороший подход по бэму, а то блок__элемент_модификатор, а не блок__блок__блок__элемент. Нейминг должен описывать блок, а не копировать теги его родителей

2021-09-16 11:33 UTC, Aliaksandrlosich commented on index.html
> +                    <span class="footer__info__content">(c) 2020 OJJO jewelry</span>
Очень не красивые скачки по ховеру

2021-09-16 11:33 UTC, Aliaksandrlosich commented on index.html
> +                        <li class="main__useful_tips_suggestions__li">Личный менеджер</li>
Из-за ховера скачет вёрстка

2021-09-16 11:33 UTC, Aliaksandrlosich commented on index.html
> +                    <li class="header__nav__li">Дизайнерам</li>
По ховеру скачет верстка

2021-09-16 11:33 UTC, Aliaksandrlosich commented on style/media.css
> +@media (max-width: 1024px) {
отлично что отдельный файл для медиа, но в идеале, можно ещё на каждый формат, отдельный файл

2021-09-16 11:33 UTC, Aliaksandrlosich commented on style/style.css
> +    color: green;
Много ссылок по ховеру зелёные, представлены в разных стилях. А можно как один)

2021-09-16 12:14 UTC, vladhillary commented on index.html
> +                    <li class="header__nav__li">Контрагентам</li>
Исправлено

2021-09-16 12:18 UTC, vladhillary commented on index.html
> +                    <li class="header__nav__li">Вакансии</li>
Исправлено

2021-09-16 12:18 UTC, vladhillary commented on index.html
> +                            <img class="header__burger__logo_img" src="./img/logo.png" alt="logo">
Исправлено

2021-09-16 12:19 UTC, vladhillary commented on index.html
> +                    <span class="footer__info__content">(c) 2020 OJJO jewelry</span>
Исправлено

2021-09-16 12:19 UTC, vladhillary commented on index.html
> +                        <li class="main__useful_tips_suggestions__li">Личный менеджер</li>
Исправлено

2021-09-16 12:19 UTC, vladhillary commented on index.html
> +                    <li class="header__nav__li">Дизайнерам</li>
Исправлено

2021-09-16 13:35 UTC, vladhillary commented on index.html
> +                    <span class="header__panel__sign_in_content">Вход/Регистрация</span>
Исправлено

2021-09-16 13:37 UTC, vladhillary commented on index.html
> +                <div class="container">
Это дефолтный контейнер, который отвечает за ограничение контентной области по всему документу

2021-09-16 13:39 UTC, vladhillary commented on index.html
> +                            <span class="main__events__li_content">мужу</span>
Мне кажется ссылки это только навигация и в футере на соц сети иконки, а это просто кнопка для перехода в каталог

2021-09-16 13:46 UTC, vladhillary commented on index.html
> +                <h2 class="main__useful_articles__best_advice">Лучшие советы по подбору дорогих подарков</h2>
Исправлено

2021-09-16 13:47 UTC, vladhillary commented on style/style.css
> +    color: green;
Стили строго по макету, единственное что можно разные ховеры наверное сделать для ссылок с разными стилями - но есть ли смысл?

2021-09-16 13:53 UTC, vladhillary commented on index.html
> +                        <img class="header__burger__social_ico" src="./img/burger_youtube.png" alt="social ico">
Исправлено

2021-09-16 14:06 UTC, vladhillary commented on style/media.css
> +@media (max-width: 1024px) {
Исправлено

2021-09-16 14:14 UTC, vladhillary commented on index.html
> +                <div class="container">
Исправлено

2021-09-16 14:49 UTC, vladhillary commented on style/style.css
> +    color: green;
Исправлено

2021-09-17 06:57 UTC, vladhillary commented on index.html
> +        <section class="header__section">
Исправлено

2021-09-17 06:57 UTC, vladhillary commented on index.html
> +                            <span class="main__events__li_content">мужу</span>
Исправлено

2021-09-20 07:12 UTC, Aliaksandrlosich commented
Стоит ещё поработать над неймингов классов.

2021-09-20 07:12 UTC, merged